blueprint:
  name: Async Wait Service
  source_url: https://raw.githubusercontent.com/vqvu/home-assistant-blueprints/master/async_wait_service.yaml
  description: >
    A service that replies to a ping after a specified amount of time.
    The time to wait is extracted from the request.

    Request event_data:
      headers:
        from: The ID of the caller. Will be reflected in the responsed.
      payload:
        delay: Amount of time to delay
        reply: The reply to be reflected in the response payload.

    Response event_data:
      headers:
        from: The ID of this automation.
        to: The ID of the caller
      payload: $request.payload.reply
  domain: automation
  input:
    request_event_type:
      name: "Request event type"
      description: "The event type to listen to."
      default: "vqvu.async_wait.ping_request"
      selector:
        text:
          type: text
    response_event_type:
      name: "Response event type"
      description: "The event type to reply to."
      default: "vqvu.async_wait.ping_response"
      selector:
        text:
          type: text

mode: parallel
max_exceeded: warning
max: 1000

trigger:
  - id: recv_request
    platform: event
    event_type: !input request_event_type

action:
  - alias: Wait for requested delay
    delay: '{{ trigger.event.data.payload.delay }}'
  - alias: Reply to request
    event: !input response_event_type
    event_data:
      headers: >
        {{
          {
            'from': this.attributes.id,
            'to': trigger.event.data.headers.from,
          }
        }}
      payload: "{{ trigger.event.data.payload.reply }}"
