blueprint:
  name: Snooze button
  source_url: https://raw.githubusercontent.com/vqvu/home-assistant-blueprints/master/snooze.yaml
  description: Implements a snooze button.
  domain: automation
  input:
    target_button:
      name: Button
      selector:
        entity:
          domain: input_boolean

    snooze_timer:
      name: Snooze timer
      selector:
        entity:
          domain: timer

mode: queued
max_exceeded: warning

trigger:
  - platform: state
    id: "button_state_changed"
    entity_id: !input target_button
    to:
      - "on"
      - "off"

  - platform: event
    event_type: timer.finished
    id: "timer_finished"
    event_data:
      entity_id: !input snooze_timer

action:
  - alias: "Check which trigger fired"
    choose:
      - alias: "Button changed state"
        conditions:
          - condition: trigger
            id: button_state_changed
        sequence:
          - alias: "Cancel the timer if it's still running"
            service: timer.cancel
            target:
              entity_id: !input snooze_timer

          - alias: "If button is on"
            if:
              - condition: state
                entity_id: !input target_button
                state: "on"
            then:
              - alias: "Start the timer"
                service: timer.start
                target:
                  entity_id: !input snooze_timer
      - alias: "Timer finished"
        conditions:
          - condition: trigger
            id: timer_finished
        sequence:
          - alias: "Turn off the button"
            service: input_boolean.turn_off
            target:
              entity_id: !input target_button
